import "~/styles/globals.css";
import Navbar from "./_components/navbar";


import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import Singin from "./_components/singin";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Navbar>
          <Singin />
        </Navbar>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
