import "~/styles/globals.css";
import Navbar from "./_components/navbar";
import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";
import Signin from "./_components/SignIn";
import ClientSessionProvider from "./_components/clientProvider";
import "@uploadthing/react/styles.css";

export const metadata = {
  title: "ACM | Web Page",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "images/logos/ACM_logo_A.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ClientSessionProvider>
          <div className="pb-16">
            <Navbar>
              <Signin />
            </Navbar>
          </div>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
