import "~/styles/globals.css";
import Navbar from "./_components/navbar";


import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import Signin from "./_components/Singin";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="pb-16">
          <Navbar>
            <Signin/>
          </Navbar>
        </div>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}

